### ISSUE TITLE
Miss some files: from models.models import *

### ISSUE THREAD

**Issue by siyuyuan** [taczin/SCAN_analogies#1]
Hi, thanks for your great work. I want to run the evaluation experiments but the error is
`from models.models import *
ModuleNotFoundError: No module named 'models'`

I think there is a file called models.py missing. Can you upload this file?

**Comment by taczin** [comment]
Hi, I added the models file. It basically only consists of the Glove model, since the Transformer models are imported ready-to-use from huggingface.
